// Auto-generated by locales — i18n routing middleware
import { NextResponse } from 'next/server';
import type { NextRequest } from 'next/server';

const locales = ['es'];
const defaultLocale = 'es';

export function middleware(request: NextRequest) {
  const { pathname } = request.nextUrl;

  const pathnameHasLocale = locales.some(
    (locale) => pathname.startsWith(`/${locale}/`) || pathname === `/${locale}`
  );

  if (pathnameHasLocale) return;

  const locale = defaultLocale;
  request.nextUrl.pathname = `/${locale}${pathname}`;
  return NextResponse.redirect(request.nextUrl, 301);
}

export const config = {
  matcher: ['/((?!_next|api|favicon.ico).*)'],
};
