// Auto-generated by locales — SEO Head tags
import * as React from 'react';

export function I18nSeo({ currentPath, domain }: { currentPath: string, domain: string }) {
  const locales = ['es'];
  const cleanPath = currentPath.replace(/^\/[a-z]{2}\//, '/');

  return (
    <React.Fragment>
      {locales.map(loc => (
        <link key={loc} rel="alternate" hrefLang={loc} href={`${domain}/${loc}${cleanPath}`} />
      ))}
      <link rel="alternate" hrefLang="x-default" href={`${domain}/en${cleanPath}`} />
    </React.Fragment>
  );
}
