// Auto-generated by locales — do not edit manually
let _translations: Record<string, string> = {};

/**
 * Load a locale dictionary into the translation runtime.
 * Call this once in your root layout/entry with the imported locale JSON.
 */
export function loadTranslations(map: Record<string, string>): void {
  _translations = map;
}

/**
 * Returns the translated string for the given hash.
 * Falls back to the hash itself if no translation is found — never crashes.
 */
export function t(hash: string): string {
  return _translations[hash] ?? hash;
}
