// Auto-generated by locales — i18n locale loader for Next.js App Router
import { loadTranslations } from '../lib/i18n';

const SUPPORTED_LOCALES = ['es'] as const;
type SupportedLocale = typeof SUPPORTED_LOCALES[number];

async function getTranslations(locale: string): Promise<Record<string, string>> {
  const supported = SUPPORTED_LOCALES.includes(locale as SupportedLocale)
    ? (locale as SupportedLocale)
    : SUPPORTED_LOCALES[0];
  try {
    const dict = await import(`../../public/locales/${supported}.json`);
    return dict.default ?? dict;
  } catch {
    return {};
  }
}

// Wrap this around your RootLayout component to activate i18n:
//
// export default async function RootLayout({ children, params }: {...}) {
//   const locale = params.locale ?? 'en';
//   loadTranslations(await getTranslations(locale));
//   return (...existing layout jsx...);
// }
//
// See: https://nextjs.org/docs/app/building-your-application/routing/internationalization

export { getTranslations };
